### ISSUE TITLE
"Add to MetaMask" in hover

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-nft-ui#36]
Consider to add the "Add to MetaMask" icon with the corresponding action to the hover of tokens thumbnails.

**Comment by dan13ram** [comment]
Hey afaik Metamask does not support erc721 or erc1155.

**Comment by akolotov** [comment]
> Hey afaik Metamask does not support erc721 or erc1155.

This is the tokens list in my MM:
![image](https://user-images.githubusercontent.com/20793260/123807406-7e74b980-d8f8-11eb-8c66-784589f85d16.png)

**Comment by dan13ram** [comment]
So you've added it as erc20 tokens. What have you put as the decimal value? also what should be done with tokens that dont have a symbol like many erc1155s?

**Comment by akolotov** [comment]
I don't think that I have added them - they were discovered automatically.

**Comment by dan13ram** [comment]
Hmm. Thats weird. From the metamask docs they only support erc20 tokens for now. And this looks like these tokens were incorrectly added as erc20 since they probably support erc20 metadata api (name, symbol and decimals).
Can you provide me with the address of those tokens ?

Ref: https://docs.metamask.io/guide/rpc-api.html#wallet-watchasset
```
type: 'ERC20'; // In the future, other standards will be supported
```

**Comment by dan13ram** [comment]
@akolotov if you think this is best then I can add the option to add the nfts as "ERC20" with decimals set to 0.

**Comment by akolotov** [comment]
Ok. I see what you mean. Let's close this issue in this case till the new functionality in MM appears.

**Comment by dan13ram** [comment]
Sounds good
