### ISSUE TITLE
[Beta Feedback]: The Hash Avatars

### ISSUE THREAD

**Issue by igorbarinov** [omni/omnibridge-nft-ui#52]
Satisfied: 
Very satisfied

Bugs/Issues:

Additional comments:
It  is possible to bridge from rinkeby to xdai mainet and the other way. Maybe it will be better to allow bridge between testnets instead of testnet to mainet. Thank you very much!!

Attachment:

**Comment by akolotov** [comment]
OpenSea has a deployment for Rinkeby that is why we decided to establish Rinkeby-xDai NFT bridge in order to allow project to test if their tokens will be picked up by OpenSea on Rinkeby.
We have a contracts for Kovan-Sokol bridge deployed but the UI app is not configured yet to use them.

**Comment by akolotov** [comment]
@dan13ram please consider to add support of the Kovan-Sokol bridge in the app

**Comment by dan13ram** [comment]
@akolotov I've added support for Kovan-Sokol.
Only caveat is the sokol subgraph we are using wouldn't sync properly due to some issues with RPC.
So I had to update it to sync only after 20000000 which is about 4 months ago. Therefore only nfts that were either minted or transfers after that point will show up on the UI. 

You can check at https://xdai-omnibridge-nft-staging.web.app/
